# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/thumu/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-24624-DESKTOP-BNTLCTA/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.cache/wt [current_project]
set_property parent.project_path D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/ALU.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/new/Adder_4_bit.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/D_FF.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Decoder_2_to_4.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Decoder_3_to_8.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Eight_way_4_bit_Mux.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/FA.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/HA.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Ins_decoder.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Program_Counter.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Program_ROM.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Reg_by_DFF.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Register_Bank.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/SevenSeg.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Slow_Clk.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Two_way_4_bit_Mux.vhd
  D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/sources_1/imports/CODD_Project/Processor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/constrs_1/new/Basys3.xdc
set_property used_in_implementation false [get_files D:/Xilinx_Projects/DevelopedProcessor/DevelopedProcessor.srcs/constrs_1/new/Basys3.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
